State/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('student.urls')),
    
]

State/mysite/student/urls.py
from django.urls import path, include
from student.models import Student
from student import views

app_name = 'student'

urlpatterns = [
    path('index/',views.ClassIndexView.as_view(),name='index'),
    path('detail/<int:student_id>/',views.ClassDetailView.as_view(),name='detail'),
    path('update/<int:student_id>/',views.UpdateDetailView.as_view(),name='update'),
    path('additem',views.Additem.as_view(),name='additem'),
    path('delete/<int:student_id>/',views.DeleteItemView.as_view(),name='delete')
]

State/mysite/student/models.py
from django.db import models
from datetime import *

class Student(models.Model):
    name = models.CharField(max_length=255)
    Class = models.PositiveIntegerField(default=1)
    RollNo = models.PositiveIntegerField(default=1)
    Address = models.CharField(max_length=500)
    PhoneNo = models.IntegerField()
    DOB = models.CharField(max_length=12)
    Image = models.CharField(max_length=5000, default="https://dm0qx8t0i9gc9.cloudfront.net/thumbnails/video/qmraJpx/videoblocks-portrait-of-smiling-male-college-student-in-busy-communal-campus-building_s-zrzm3vi_thumbnail-1080_01.png")
    
    def __str__(self):
        return self.name

State/mysite/student/forms.py
from student.models import Student
from django import forms
class ItemForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['name','Class','RollNo','Address','PhoneNo','DOB','Image']

State/mysite/student/views.py
from typing import Any
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from .models import Student
from django.urls import reverse_lazy
from student.forms import ItemForm


class ClassIndexView(ListView):
    model = Student
    context_object_name = 'StudentList'
    template_name = 'student/index.html'


class ClassDetailView(DetailView):
    model = Student
    context_object_name = 'student'
    pk_url_kwarg = 'student_id'
    template_name = 'student/detail.html'


class UpdateDetailView(UpdateView):
    model = Student
    form_class = ItemForm
    template_name = 'student/item-form.html'
    success_url = reverse_lazy('student:index')
    
    def get_object(self, queryset=None):
        student_id = self.kwargs.get('student_id')
        return Student.objects.get(id=student_id)

class Additem(CreateView):
    model = Student
    fields = '__all__'
    template_name = 'student/item-form.html'
    success_url = reverse_lazy('student:index')
    
    def form_valid(self, form):
        form.instance.added_by = self.request.user.username
        return super().form_valid(form)

class DeleteItemView(DeleteView):
    model = Student
    template_name = 'student/item-delete.html'
    success_url = reverse_lazy('student:index')
    
    
    def get_object(self, queryset=None):
        student_id = self.kwargs.get('student_id')
        return Student.objects.get(id=student_id)
    

State/mysite/student/templates/student/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'student:index' %}">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class=" collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ms-auto ">
            <li class="nav-item">
            <a class="nav-link mx-2 active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
            <a class="nav-link mx-2" href="{% url 'student:additem' %}">Add item</a>
            </li>
            <li class="nav-item">
            <a class="nav-link mx-2" href="#">Pricing</a>
            </li>
            <li class="nav-item dropdown">
            <a class="nav-link mx-2 dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Company
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><a class="dropdown-item" href="#">Blog</a></li>
                <li><a class="dropdown-item" href="#">About Us</a></li>
                <li><a class="dropdown-item" href="#">Contact us</a></li>
            </ul>
            </li>
        </ul>
        </div>
    </div>
</nav>

{% block body %}
  
{% endblock  %}
</body>
</html>

State/mysite/student/templates/student/detail.html
{% extends "student/base.html" %}
{% block body %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .bootdey {
            display: flex;
            justify-content: space-between;
        }
        .pro-img-details {
            width: 50%;
        }
        .pro-details {
            width: 50%;
        }
    </style>
</head>
<body>
    <div class="container bootdey mt-5">
        <div class="pro-img-details">
            <section class="panel">
                <div class="panel-body">
                    <div class="pro-img-details">
                        <img src="{{ student.Image }}" alt="" style="height: 250px; width: 500px;">
                    </div>
                </div>
            </section>
        </div>
        <div class="pro-details">
            <section class="panel">
                <div class="panel-body">
                    <h4 class="pro-d-title">
                        State Name:{{ student.name }}
                    </h4>
                    <p>
                        Population: {{ student.RollNo }}
                    </p>
                    <div class="product_meta">
                        <span class="posted_in"> <strong>Language:</strong> {{ student.Address }}</span>
                        <span class="tagged_as"><strong> Capital :</strong> {{ student.DOB }}</span>
                    </div>
                    <div class="mt-5">

                    </div>
                    <p>
                        <a href="{% url 'student:index' %}"><button class="btn btn-round btn-danger" type="button"><i class="fa fa-shopping-cart"></i>back</button></a>
                        <a href="{% url 'student:update' student.id %}"><button class="btn btn-round btn-danger" type="button"><i class="fa fa-shopping-cart"></i> Update</button></a>
                        <button class="btn btn-round btn-danger" type="button"><i class="fa fa-shopping-cart"></i> Delete</button>
                    </p>
                </div>
            </section>
        </div>
    </div>
</body>
</html>

{% endblock  %}

State/mysite/student/templates/student/index.html
{% extends "student/base.html" %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css" integrity="sha256-2XFplPlrFClt0bIdPgpz8H7ojnk10H69xRqd9+uTShA=" crossorigin="anonymous" />
</head>
<body>
    <div class="row">
        <div class="container mt-3 mb-4">
            <div class="col-lg-9 mt-4 mt-lg-0">
                <div class="row">
                    <div class="col-md-12">
                <div class="user-dashboard-info-box table-responsive mb-0 bg-white p-4 shadow-sm">
                  <table class="table manage-candidates-top mb-0">
                    <thead>
                      <tr>
                          <th>State Name</th>
                        <th class="text-center">Status</th>
                        <th class="action text-right" style="padding-right: 0px;"><span>Action</span></th>
                    </tr>
                    </thead>
                    {% for Student in StudentList %}
                    <tbody>
                      <tr class="candidates-list">
                        <td class="title">
                          <div class="thumb">
                            <img class="img-fluid" src="{{ Student.Image }}" alt="">
                          </div>
                          <div class="candidate-list-details">
                            <div class="candidate-list-info">
                              <div class="candidate-list-title">
                                <h5 class="mb-0"><a href="#">{{ Student.name }}</a></h5>
                              </div>
                              <div class="candidate-list-option">
                                <ul class="list-unstyled">
                                  <li><i class="fas fa-filter pr-1"></i>{{ Student.Class }}</li>
                                  <li><i class="fas fa-map-marker-alt pr-1"></i>{{ Student.Address }}</li>
                                </ul>
                              </div>
                            </div>
                          </div>
                        </td>
                        <td class="candidate-list-favourite-time text-center">
                          <a class="candidate-list-favourite order-2 text-danger" href="#"><i class="fas fa-heart"></i></a>
                          <span class="candidate-list-time order-1">Active</span>
                        </td>
                        <td>
                          <ul class="list-unstyled mb-0 d-flex justify-content-end">
                            <li><a href="{% url 'student:detail' Student.id %}" class="text-primary" data-toggle="tooltip" title="" data-original-title="view"><i class="far fa-eye"></i></a></li>
                            <li><a href="{% url 'student:update' Student.id %}" class="text-info" data-toggle="tooltip" title="" data-original-title="Edit"><i class="fas fa-pencil-alt"></i></a></li>
                            <li><a href="{% url 'student:delete' Student.id %}" class="text-danger" data-toggle="tooltip" title="" data-original-title="Delete"><i class="far fa-trash-alt"></i></a></li>
                          </ul>
                        </td>
                      </tr>
                      
        {% endfor %}
    </div>
        
</body>
<style>
    body{
        background-color: #f8f9fa!important
    }
    .p-4 {
        padding: 1.5rem!important;
    }
    .mb-0, .my-0 {
        margin-bottom: 0!important;
    }
    .shadow-sm {
        box-shadow: 0 .125rem .25rem rgba(0,0,0,.075)!important;
    }    
    /* user-dashboard-info-box */
    .user-dashboard-info-box .candidates-list .thumb {
        margin-right: 20px;
    }
    .user-dashboard-info-box .candidates-list .thumb img {
        width: 80px;
        height: 80px;
        -o-object-fit: cover;
        object-fit: cover;
        overflow: hidden;
        border-radius: 50%;
    }
    
    .user-dashboard-info-box .title {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        padding: 30px 0;
    }
    
    .user-dashboard-info-box .candidates-list td {
        vertical-align: middle;
    }
    
    .user-dashboard-info-box td li {
        margin: 0 4px;
    }
    
    .user-dashboard-info-box .table thead th {
        border-bottom: none;
    }
    
    .table.manage-candidates-top th {
        border: 0;
    }
    
    .user-dashboard-info-box .candidate-list-favourite-time .candidate-list-favourite {
        margin-bottom: 10px;
    }
    
    .table.manage-candidates-top {
        min-width: 650px;
    }
    
    .user-dashboard-info-box .candidate-list-details ul {
        color: #969696;
    }
    
    /* Candidate List */
    .candidate-list {
        background: #ffffff;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        border-bottom: 1px solid #eeeeee;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        padding: 20px;
        -webkit-transition: all 0.3s ease-in-out;
        transition: all 0.3s ease-in-out;
    }
    .candidate-list:hover {
        -webkit-box-shadow: 0px 0px 34px 4px rgba(33, 37, 41, 0.06);
        box-shadow: 0px 0px 34px 4px rgba(33, 37, 41, 0.06);
        position: relative;
        z-index: 99;
    }
    .candidate-list:hover a.candidate-list-favourite {
        color: #e74c3c;
        -webkit-box-shadow: -1px 4px 10px 1px rgba(24, 111, 201, 0.1);
        box-shadow: -1px 4px 10px 1px rgba(24, 111, 201, 0.1);
    }
    
    .candidate-list .candidate-list-image {
        margin-right: 25px;
        -webkit-box-flex: 0;
        -ms-flex: 0 0 80px;
        flex: 0 0 80px;
        border: none;
    }
    .candidate-list .candidate-list-image img {
        width: 80px;
        height: 80px;
        -o-object-fit: cover;
        object-fit: cover;
    }
    
    .candidate-list-title {
        margin-bottom: 5px;
    }
    
    .candidate-list-details ul {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -ms-flex-wrap: wrap;
        flex-wrap: wrap;
        margin-bottom: 0px;
    }
    .candidate-list-details ul li {
        margin: 5px 10px 5px 0px;
        font-size: 13px;
    }
    
    .candidate-list .candidate-list-favourite-time {
        margin-left: auto;
        text-align: center;
        font-size: 13px;
        -webkit-box-flex: 0;
        -ms-flex: 0 0 90px;
        flex: 0 0 90px;
    }
    .candidate-list .candidate-list-favourite-time span {
        display: block;
        margin: 0 auto;
    }
    .candidate-list .candidate-list-favourite-time .candidate-list-favourite {
        display: inline-block;
        position: relative;
        height: 40px;
        width: 40px;
        line-height: 40px;
        border: 1px solid #eeeeee;
        border-radius: 100%;
        text-align: center;
        -webkit-transition: all 0.3s ease-in-out;
        transition: all 0.3s ease-in-out;
        margin-bottom: 20px;
        font-size: 16px;
        color: #646f79;
    }
    .candidate-list .candidate-list-favourite-time .candidate-list-favourite:hover {
        background: #ffffff;
        color: #e74c3c;
    }
    
    .candidate-banner .candidate-list:hover {
        position: inherit;
        -webkit-box-shadow: inherit;
        box-shadow: inherit;
        z-index: inherit;
    }
    
    .bg-white {
        background-color: #ffffff !important;
    }
    .p-4 {
        padding: 1.5rem!important;
    }
    .mb-0, .my-0 {
        margin-bottom: 0!important;
    }
    .shadow-sm {
        box-shadow: 0 .125rem .25rem rgba(0,0,0,.075)!important;
    }
    
    .user-dashboard-info-box .candidates-list .thumb {
        margin-right: 20px;
    }
</style>
</html>
{% endblock  %}

State/mysite/student/templates/student/item-delete.html
{% extends "student/base.html" %}
{% block body %}

<form action="" method="POST">
    {% csrf_token %}
    Are ypu sure you want to delete
    <button type="submit">Yes, Conform</button>
</form>
  
{% endblock  %}

State/mysite/student/templates/student/item-form.html
{% extends "student/base.html" %}
{% block body %}
  <form action="" method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">submit</button>
  </form>
{% endblock  %}